package mx.edu.uaz.GymNutrition2.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PrincipalUser extends HorizontalLayout {
	protected Label lblGn;
	protected Button menuButton;
	protected CssLayout menu;
	protected Button btnRutinas;
	protected Button btnVerDietas;
	protected Label lblCont;
	protected CssLayout content;
	protected CssLayout contentUser;

	public PrincipalUser() {
		Design.read(this);
	}
}
